name: RL_PROTECT_JOB
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_deps" to run before any build job
  check_deps:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      # ---------------------------------------
      - name: gh-action-rl-protect-scan-test
        uses: reversinglabs/gh-action-rl-protect-scan@v1
        id: rl-protect-test
        env: # pass env var secrets
          RL_TOKEN: ${{ secrets.RL_TOKEN }}
        with: # pass ordinary params
          rl-server: 'my.secure.software/test'
          rl-org: 'Test'
          rl-group: 'Default'
          scan-path: 'requirements.txt'
          scan-profile: 'baseline'
          report: 'my-report.json'
          check-deps: 'develop,release'
          log-file: 'my-log-file.txt'
          log-level: 'pass'
          verbose: true
          concise: true

      # ---------------------------------------
      - name: Run a multi-line script to show the result of the rl-protect action
        run: |
            echo "Status of rl-protect: ${{steps.rl-protect-test.outputs.status}}"
            echo "Description of rl-protect: ${{steps.rl-protect-test.outputs.description}}"
            ls -la
            exit 0
    # build job
